### ISSUE TITLE
Not recognising function neuralynx_getheader when converting NRD to NSD files

### ISSUE THREAD

**Issue by dervinism** [fieldtrip/fieldtrip#2482]
After downloading and installing (running ```ft-defaults``` function) fieldtrip and executing ```ft_spikesplitting``` function to convert NRD files to NSD as described on your website [here](https://www.fieldtriptoolbox.org/getting_started/intracranial/neuralynx_fcdc/#:~:text=The%20Neuralynx%20acquisition%20system%20provides,information%20extracted%20from%20a%20single%20.), I get the following error:
```
Unrecognized function or variable 'neuralynx_getheader'.

Error in read_neuralynx_dma (line 77)
  orig = neuralynx_getheader(filename);

Error in ft_spikesplitting (line 235)
  buf = read_neuralynx_dma(cfg.dataset, begsample, endsample, 'all');

Error in nrd2nsd_fieldtrip (line 6)
cfg         = ft_spikesplitting(cfg);
```

**Environment and versions:**
 - Operating System: macOS 15.3.1
 - MATLAB version: R2024a
 - FieldTrip version: 1f8a83aa2

**Comment by robertoostenveld** [comment]
Hi Martynas,

Thanks for your report. I must admit that it has been ages since we have used that function, as we don't have a Neuralynx recording setup any more. But I don't see a reason it would not work any more.

The files `neuralynx_getheader.m` and `neuralynx_crc.m` were left behind in `fieldtrip/private' and should be moved over to 'fieldtrip/contrib/spike/private'. I will update FieldTrip accordingly and it shoud be fixed in the next release, in the mean time you can move those files by hand.

best regards,
Robert

**Comment by dervinism** [comment]
Hi Robert,

Thank you for a quick reply. I moved those m files to ```fieldtrip/contrib/spike/private``` but I am still getting the same error message.

**Comment by dervinism** [comment]
Those files should actually be copied rather than moved as they are slo needed by another function ```read_neuralynx_dma```. Copying rather than moving seems to have fixed this particular issue.

**Comment by dervinism** [comment]
That's right
